import { generator } from "./customRouter1.js";
import express from "express";
import { readFileSync } from "fs";
import { MongoClient, ObjectId } from "mongodb";
var { api_port, mongodb_url, mongodb_db_name } = JSON.parse(readFileSync("./env.json", "utf-8"));
var client = new MongoClient(mongodb_url);
var db = client.db(mongodb_db_name);
var app = express();
app.use(generator(db));
app.listen(api_port, () => console.log(`server started listening on port ${api_port} ...`));
